name: Publisher

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish:
    # Name the Job
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release src/p1eXu5.Wpf.DigitPanel/p1eXu5.Wpf.DigitPanel.csproj --output .
      
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}} --skip-duplicate
